### ISSUE TITLE
Slice indexing support

### ISSUE THREAD

**Issue by karashiiro** [FractalFir/rustc_codegen_clr#13]
#### Overview
Currently, slice indexing is not supported by codegen, e.g. the following code will fail to compile because `PlaceElem::ConstantIndex` hasn't been implemented:
```rust
#[no_mangle]
pub extern fn assign_slice_elem(place: &mut [u8], value: &[u8]) {
    place[0] = value[0];
}
```

I was looking at how `PlaceElem::Index` was implemented hoping to reuse most of that code for this, but that generates references to `RustSlice<G0>::GetLength()` and `RustSlice<G0>::get_Item()`, which aren't implemented. `ilasm` successfully assembles the resulting IL, but fails silently after that, presumably due to the unresolved references.

#### Questions
Do we have a place for implementing instance methods on builtins to get this working? I can see that `RustSlice` is a `TypeDef` in the generated stdlib, but I couldn't find any examples of `TypeDef`s with methods.

Alternatively, is there a better way to do this than reusing `PlaceElem::Index`? Before this, I was considering trying to just replace `RustSlice` with `System.Span` to leverage whatever .NET can give us, but I don't actually know if that's logically equivalent or not, which is why I opted for the `PlaceElem::Index` approach instead.

**Comment by FractalFir** [comment]
System.Span is a ref struct, so it can only be stored on the stack. Memory<T> does not have this issue, but it may have some overhead(due to auto pinning in Mono)/may not be safe to store in unmanaged memory(If it does not pin, then passing it from C# to Rust could lead to issues). This topic requires a bit moee research.
Memory<T> seems like the best option if those issues don't occur, but RustSlice type is a decent temporary workaround, and it can stay if no better solution is found.

Instance methods on a TypeDef are not yet supported, but the existing ILASM exporter should deal with them easily with a few small changes.

**Comment by karashiiro** [comment]
`Memory<T>` can support unmanaged memory, but you need your own `MemoryManager<T>` to wrap it. I've used [this](https://stackoverflow.com/a/52191681) in the past for this purpose.

I think even if I did that, I'd still need to have methods on a `TypeDef` to implement it, though - I'll have to start there either way.

**Comment by FractalFir** [comment]
The Memory Manager is a managed object, so creating a slice would introduce a hidden allocation, which is not something Rust allows (All allocations should be explicit). Furthermore, the documentation only states:
```
This means that Memory<T> can be placed on the managed heap, whereas Span<T> cannot.
```
Rust code will sometimes store slices on the unmanaged heap. This could lead to numerous issues, since someone could pass a slice backed by a managed array to Rust, which could in turn store it in unmanaged memory, leading GC to move/free the underlying array when it is still in use.

**Comment by karashiiro** [comment]
I think it's possible to handle passing arbitrary slices into unmanaged code; `LoadLibraryAttribute` has Roslyn sourcegen specifically for `Span<T>` which handles pinning appropriately. `MemoryManager` itself being an allocation is a nonstarter though, I hadn't considered that 😢

More generally, how are lifetimes going to be handled at interop boundaries? Anything passed from managed code into unmanaged code has an unknown lifetime and is unsafe to dereference, unless you enforce copying when passing objects between contexts.

**Comment by karashiiro** [comment]
Actually, even the generated interop for spans doesn't handle pointers being stored for longer than the duration of the invocation, so that's not an option at all.

**Comment by FractalFir** [comment]
> More generally, how are lifetimes going to be handled at interop boundaries? Anything passed from managed code into unmanaged code has an unknown lifetime and is unsafe to dereference, unless you enforce copying when passing objects between contexts.

C# currently does not support move semantics, which makes it impossible to enforce almost anything. All Rust structs, even those which do not implement the `Copy` trait, can be implicitly copied in C#. Enforcing lifetimes will thus need to fall on the person interoping with a particular rust lib.

There are ways of wrapping managed classes around Rust types with lifetimes, but since the runtime does not guarantee finalizers run in any particular order, it requires special care to ensure everything is disposed of correctly.
